server:
  port: 15080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chattie_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    out-of-order: true
    sql-migration-prefix: T
    table: flyway_schema_chattie
    validate-on-migrate: false