server:
  port: 15080

spring:
  ai:
    ollama:
      model: ${OLLAMA_MODEL:llama3.2}

  datasource:
    url: jdbc:postgresql://localhost:5432/chappie_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    out-of-order: true
    sql-migration-prefix: T
    table: flyway_schema_chappie
    validate-on-migrate: false